project:
  type: website

website:
  title: "GEOG 531"
  navbar:
    background: primary
    search: true
    left:
    - text: "Home"
      href: index.qmd
    - text: "Materials"
      menu:
      - text: "Lectures"
        href: lectures.qmd
      - text: "Readings"
        href: readings.qmd
     
  


      
      
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: visual

