project:
  type: website

website:
  title: "GEOG 510"
  navbar:
    background: primary
    search: true
    left:
    - text: "Schedule"
      menu:
      - about.qmd
      - about.qmd
    - text: "Materials"
      menu:
      - about.qmd
      - about.qmd
    - text: "Schedule"
      menu:
      - about.qmd
      - about.qmd
      
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: visual

