project:
  type: website

website:
  title: "GEOG 510"
  navbar:
    background: primary
    search: true
    left:
    - text: "Home"
      href: index.qmd
    - text: "Materials"
      menu:
      - text: "Lectures"
        href: lectures.qmd
      - text: "Readings"
        href: readings.qmd
      - text: "Exercises"
        href: exercises.qmd
      - text: "Assignments"
        href: assignments.qmd
      
    - text: "Resources"
      menu:
      - software.qmd
      - data.qmd
      - tutorials.qmd
      - mapping.qmd
      
      
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: visual

