project:
  type: website

website:
  title: "GEOG 510"
  navbar:
    background: primary
    search: true
    left:
    - text: "Schedule"
      href: schedule.qmd
    - text: "Materials"
      menu:
      - lectures.qmd
      - readings.qmd
      
    - text: "Resources"
      menu:
      - software.qmd
      - data.qmd
      
      
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: visual

