---
title: "Homeworks"
date: last-modified
date-format: medium
---

------------------------------------------------------------------------

# List of Homeworks

------------------------------------------------------------------------

### Homework 1: Once Upon a Stormy Evening (Due September 25, 11:59 pm)

- [*Part A: Descriptive statistics and Visualization*](./hw/hw1/hw1_partA.qmd){target="_blank"}
  - [*Part B: Descriptive mapping and spatial Statistics*](./hw/hw1/hw1_partB_revised.qmd){target="_blank"}

    - **Important Errata**: In your posit cloud Homework 1B, go to the folder Code and check the descriptive_geo_functions.R script. Then check for the following comments at the beginning.

```{r}
    # ------------------------
    # NOTE: IF YOU SEE THIS LINE THEN THIS IS THE CORRECT FILE WITH THE CORRECT
    # WEIGHTED STANDARD DEVIATIONAL ELLIPSE FUNCTION
    # ----------------------------------------------------------
```

- If the script DOES NOT show the above comments at the start:
- Download the [*correct file here*](./hw/hw1/code/descriptive_geo_functions.R){target="_blank"}, delete the old script, and upload the downloaded file in the Code folder.
- If your original script already shows the comments, you dont need to do anything else.

**Answer Keys:** [Part A,](./hw/hw1/hw1_answers.qmd){target="_blank"} [Part B](./hw/hw1/hw1_partB_answers.qmd){target="_blank"}

### Final Project: Quantitative Geographic Showcase (Due December 8, 11:59 pm)

- [*Qunatitative Geographic Showcase*](./hw/GEOG531_Quantitative_Geography_Showcase_Instructions.pdf){target="_blank"}
