---
title: 'GEOG 531: Final Project Analysis Plan'
author: "Varun Goel"
description: |
  Due Date: **Monday, November 24, 11: 59 pm** \newline \newline
  **(250 points + 20 bonus points)**
date: 'Updated: `r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    theme: flatly
    highlight: null
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

------------------------------------------------------------------------

## Project Analysis Plan

The purpose of this Analysis plan is to serve as your analysis workhorse for your final project. In general, before conducting a quantitative analysis, it is good practice to have such a pre-specified plan even before you 'actually' conduct the analysis. This not only helps you think deeply about your analysis and give you direction, but it helps you not 'cherry pick' your results, where researchers only tend to show positive results, and not the null results.

You can follow the same headings for your analysis plan, but can also add your own for your specific project if it makes sense.

Submit your analysis plan as markdown file that is also knitted into an html file.

[1) **Main Research Question (20 points)**]{.underline}

We have done a lot of practice on this. Your question should be about how a 'process' may influence the 'pattern' that you see. It should also have some context about the spatial or temporal aspect of your question or the population that you may be interested. This will be similar to the question for your project that you generate in HW 1. You can also have [optional]{.underline} 1 or 2 sub-questions, that should be linked to the main questions.

For example, my main research question is *"Does greater social vulnerability cause greater property damage to floods in South Carolina between 2020 and 2024"?*

Follow-up sub questions could be:

-   Is the relationship between social vulnerability and flooding damage different in 2020 compared to 2024?

-   Is the relationship between social vulnerability and flooding different than the relationship between social vulnerability and flash flooding?

[2) **Causal Diagram (60 points)**]{.underline}

This is the most important part of your analysis plan and I propose that you spend some time on it. If you follow the instructions below, you should be in good shape. I want to see that you thought sensibly and deeply about the causal system of your research question at hand, and that you made your assumptions clear to me!

-   Use the software [DAGitty](https://www.google.com/search?client=safari&rls=en&q=daggitty&ie=UTF-8&oe=UTF-8) to draw your DAGs. Make sure to have sensible labels for your nodes. We have already practiced it a lot but Daggity also has very good examples and a 'how to' section.

-   DAG should have your Exposure (Independent/Predictor) Variable.

-   DAG should have your Outcome (Dependent/Response) Variable.

-   DAG should have all other variables along with arrows that are part of your causal system. These variables should be theoretically motivated. Additionally, these variables should [NOT BE LIMITED]{.underline} to the data that you already have. For example, income plays a role in social vulnerability and property damage to floods. However, even if I do not have the data, I should still mention it. DAGs should contain both [OBSERVED]{.underline} and [UNOBSERVED]{.underline} variables. There is no maximum number of variables that your DAG should have but at a minimum you should have [atleast 5 more variables]{.underline} in addition to exposure and outcome. [Atleast 2 of these variables should be confounders]{.underline} (more on that in next point)

-   Report all minimum sufficient adjustment sets for the effect of the exposure variable on the outcome variable. Note that there may be more than one minimum sufficient adjustment sets.

-   Take a good quality screenshot of your causal diagram and paste it into the document.

-   In 5-8 lines, describe the justification for your DAG. Use this paragraph to make a strong case for why I should believe that your DAG is good enough. You can also use this space to talk about potential variables that you did not include but were thinking of, or any other information so that I can get a better sense of how you were thinking about your causal diagram.

2\) [**Descriptive Statistics**]{.underline} **(90 points)**

This will be an important part of your final project. Here you will describe your data to 'provide context' to the reader. This could be in the form of simple summary statistics, and maps. These descriptions of your data should motivate your data analysis and your hypothesis. Follow atleast the following instructions for outlining the plan for your descriptive statistics. Be creative and feel free to suggest any other ways in which you may choose to describe your descriptive statistics.

-   Describe what data types your descriptive variables will be. In case there is a descriptive variable that you do not have data for, that is ok. You can write about what kind of data type you would expect to see if you had the data. Note that you dont have to describe every single variable from your DAG, but you should do this atleast for your exposure, outcome, confounders, and any other important variables that you may test later. For this analysis plan you can have a table similar to the one below.

| Variable                    | Data Type                | Observed in dataset |
|-----------------------------|--------------------------|---------------------|
| Property Damage             | Ratio                    | Yes                 |
| Social Vulnerability        | Ratio                    | Yes                 |
| flood location              | Point level spatial data | Yes                 |
| Median household income     | Ratio                    | No                  |
| Rural or Urban census tract | Nominal                  | Yes                 |

-   In one line describe the 'scale' of your analysis. For example, in my example, the scale of my analysis is at 'census tract' level since I am exploring whether socially vulnerable census tracts have higher average property damage or not?

-   Describe [atleast 3 descriptive outputs]{.underline} in your final project, with [atleast 1 being a descriptive table]{.underline}. A descriptive table is common place in almost every quantitative analysis. You can look at the table 1 from my own papers such as [Goel et al. 2023](https://geog531.netlify.app/readings/Goel%20et%20al.%20-%202023%20-%20Deep%20tubewell%20use%20is%20associated%20with%20increased%20hou.pdf) but there are several options! The other outputs could be maps or figures!

    You should have 3 short paragraphs, one for each descriptive output. For the table, talk about how you would summarize your important variables. For the maps, describe what those maps would entail and what their purpose will be. Same for figures.

    For example, I would have a descriptive table that shows the mean and standard deviation of property damage and social vulnerability. For rural/urban census tracts, I may just show the count in each, and so on. For maps, I might show a choropleth map of average property damage in each census tract, and a choropleth map of social vulnerability side by side to show the spatial distribution to the readers. For the figures, I might show 2 scatter plots of social vulnerability and property damage for 2 different years, side by side.

4\) [**Data Analysis (60 points)**]{.underline}

This is the part where you will specify your regression model and any other hypothesis that you will do. Good news is that your DAG has already given you an idea of what a potential regression model(s) may look like. Here is are the steps to create an analysis plan for your regression model.

-   First you will write the formula for your main regression model based on your DAG. In a general form, your regression model formula would be:

    `Outcome ~ Exposure + confounder1 + confounder2 + confounderN`

    So, in my case for example, it could be:

    `Property Damage ~ Social Vulnerability + Income + Rural-urban tract`

    For those of you who have multiple minimum sufficient sets in your DAG, write the formula for the one with most confounders.

-   Now, think and write down a 3-5 line paragraph about the following question:

    Is there any potential for interaction among your exposure variable and another variable, and why or why not? Or in other words, would the relationship between your exposure variable and outcome be different for different levels of another variable?

    For example, I believe that the social vulnerability and rural-urban census tract might interact since I believe that social vulnerability relationships in rural tracts may be very different than how they are measure in urban tracts.

-   Lastly, write one 3-5 line paragraph about what first-order or second-order effects may be explaining the distribution of your outcome variable and its relationship with your independent variable. While we are not going to be running spatial analysis as such in this class (unless you want to \[ come see me in that case\]), I want you to think about 1st and 2nd order processes.

    For example, in my example, the relationship between social vulnerability and property damage could be influenced both my 1st and 2nd order processes. Social vulnerability is itself an external factor that makes more damage likely. However, more damage may result in more social vulnerability, and that is a 2nd order process. Additionally, if neighboring census tracts have more property damage or more social vulnerability, that may also influence the values of property damage and social vulnerability in our census tract. That is a 2nd order effect too. [In most cases, you will have BOTH 1st and 2nd order effects for your research question.]{.underline}

5\) [**Project Paper title (10 points)**]{.underline}

Finally, come up with a draft project title for your paper. We discussed this in class too and refine until final project submission.

5\) [**Submission (10 points)**]{.underline}

Make sure that your file knits as an html file succesfully.

6\) [**Extra Credit (Upto 20 points)**]{.underline}

For anything creative that you might come up with for your final project whether we covered it in class or not.
