---
title: 'Tissot Indicatrix and CRS'
author:
- In Class Exercise \#2 \newline
- GEOG 510, GIS and Spatial Analysis in Public Health \newline
- Varun Goel
output:
  html_document:
    theme: flatly
    highlight: tango
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

In this exercise, you will use QGIS to create Tissot Indicatix Circles and will explore the Coordinate Reference System (CRS) and projections functionality in QGIS.

**Note that throughout this document, if I use the term "right click," this means "control click" for Mac users!**

------------------------------------------------------------------------

### Download Data

1.  Navigate to <https://hub.arcgis.com/datasets/esri::world-countries-generalized/about>. Click the **Download** button, scroll down to GeoJSON, and click the **Download** button. Save the file as **World_Countries.geojson** to your hard drive (a great place to save would be your GEOG 510 folder).

2.  Navigate to <https://hub.arcgis.com/datasets/esri::world-latitude-and-longitude-grids/explore?layer=0>. Click the **Download** button, scroll down to GeoJSON, and click the **Download** button. Save the file as **World_Grid.geojson** to your hard drive (a great place to save would be your GEOG 510 folder).

3.  Now, [download Tissot.gpkg here](https://drive.google.com/file/d/1rCVyFBVBMC8mwW6P-be7UbFjmR9kfIRj/view?usp=sharing). A great place to save would be your GEOG 510 folder.

### Add Data Layers

4.  Open QGIS. In the top menu, select Project \| New.

5.  Add World_Countries.geojson to the Layers panel (you can do this by dragging from the Browser panel or clicking the Open Data Source Manager button).

6.  Add World_Grid.geojson to the Layers panel (you can do this by dragging from the Browser panel or clicking the Open Data Source Manager button).

7.  Add Tissot.gpkg to the Layers panel (you can do this by dragging from the Browser panel or clicking the Open Data Source Manager button).

**Q1. Open a new word file, and take a screenshot of your map and paste it. In 1-2 sentences, describe what the various sizes and shapes of the circle might tell you about the projection. Does, it preserve area, shape, both, neither?**

### Change Projection

8.  Change the projection of the Map Panel to any equal area projection! What do you notice?

**Q2. In 1-2 sentences, describe what the various sizes and shapes of the circle might tell you about the projection. Does, it preserve area, shape, both, neither?**

9.  Change the projection of the Map Panel to any conformal projection! What do you notice?

**Q3. In 1-2 sentences, describe what the various sizes and shapes of the circle might tell you about the projection. Does, it preserve area, shape, both, neither?**

Submission instruction. Save your word file as "username_ex2.docx" and upload it to your relevant OneDrive folder.

------------------------------------------------------------------------
