{
  "hash": "b872cc6eb88df22f601805b844cdc39e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Quantitative Methods in Geographic Research\"\nsubtitle: \"Inference using Linear Regression\"\nauthor:\n - name: \"Varun Goel\"\ninstitute: \"\"\ndate: 2025-10-29\ndate-format: medium\ntitle-slide-attributes:\n  data-background-color: \"#f3f4f4\"\n  data-background-size: 80%\n  data-background-position: 60% 120%\n  subparagraph: yes\nformat:\n  revealjs:\n    slide-number: true\n    incremental: false\n    footer: \"Linear Regression\"\n    chalkboard:\n      buttons: false\n      preview-links: auto\n    theme: [default, ../../assets/style.scss]\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.1     ✔ readr     2.2.0\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.3     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(moderndive)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nmoderndive's `View()` renders a DT::datatable() inline here instead of erroring like `utils::View()`.\n\nAttaching package: 'moderndive'\n\nThe following object is masked from 'package:utils':\n\n    View\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(infer)\nlibrary(ISLR2)\n \nUN_data_ch5 <- un_member_states_2024 |>\n  select(iso, \n         life_exp = life_expectancy_2022, \n         fert_rate = fertility_rate_2022, \n         obes_rate = obesity_rate_2016)|>\n  na.omit()\n```\n:::\n\n\n## To Read\n\nModernDive book - Chapter 5,6,10\n\n<https://moderndive.com/v2/regression.html>\n\nModern Statistics book - Chapter 7,8, 24, 25\n\n<https://openintro-ims.netlify.app/model-slr>\n\n## Life expectancy and fertility rates\n\nHow do changes in life expectancy influence fertility rates\n\n## Descriptive Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUN_data_ch5 |>\n  summarize(mean_life_exp = mean(life_exp), \n            mean_fert_rate = mean(fert_rate),\n            median_life_exp = median(life_exp), \n            median_fert_rate = median(fert_rate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  mean_life_exp mean_fert_rate median_life_exp median_fert_rate\n          <dbl>          <dbl>           <dbl>            <dbl>\n1          73.6           2.50            75.1                2\n```\n\n\n:::\n\n```{.r .cell-code}\nUN_data_ch5 |> \n  select(fert_rate, life_exp) |> \n  tidy_summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 11\n  column        n group type      min    Q1  mean median    Q3   max    sd\n  <chr>     <int> <chr> <chr>   <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl>\n1 fert_rate   181 <NA>  numeric   1.1   1.6  2.50    2     3.2   6.6  1.15\n2 life_exp    181 <NA>  numeric  53.6  69.4 73.6    75.1  78.3  86.4  6.80\n```\n\n\n:::\n:::\n\n\n## Are life expectancy and fertility correlated?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUN_data_ch5 |> \n  summarize(correlation = cor(fert_rate, life_exp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  correlation\n        <dbl>\n1      -0.812\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(UN_data_ch5, \n       aes(x = life_exp, y = fert_rate)) +\n  geom_point(alpha = 0.4) +\n  labs(x = \"Life Expectancy\", y = \"Fertility Rate\")\n```\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## What does the correlation tell us\n\n-   strength of linear association\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUN_data_ch5 |> \n  summarize(correlation = cor(fert_rate, life_exp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  correlation\n        <dbl>\n1      -0.812\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(UN_data_ch5, \n       aes(x = life_exp, y = fert_rate)) +\n  geom_point(alpha = 0.4) +\n  labs(x = \"Life Expectancy\", y = \"Fertility Rate\")\n```\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## What would a 'best fit' line through this look like?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(UN_data_ch5, aes(x = life_exp, y = fert_rate)) +\n  geom_point(alpha = 0.5) +\n  labs(x = \"Life Expectancy\", \n    y = \"Fertility Rate\",\n    title = \"Relationship of life expectancy and fertility rate\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n## What would a 'best fit' line through this look like?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(UN_data_ch5, aes(x = life_exp, y = fert_rate)) +\n  geom_point(alpha = 0.1) +\n  labs(x = \"Life Expectancy\", \n    y = \"Fertility Rate\",\n    title = \"Relationship of life expectancy and fertility rate\") +\n  geom_smooth(method = \"lm\", se = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## Your first linear regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit regression model:\ndemographics_model <- lm(fert_rate ~ life_exp, data = UN_data_ch5)\n# Get regression coefficients\ncoef(demographics_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)    life_exp \n 12.5992926  -0.1372879 \n```\n\n\n:::\n:::\n\n\n## Your first linear regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(UN_data_ch5, aes(x = life_exp, y = fert_rate)) +\n  geom_point(alpha = 0.5) +\n  labs(x = \"Life Expectancy\", \n    y = \"Fertility Rate\",\n    title = \"Relationship of life expectancy and fertility rate\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Your first linear regression model\n\n-   For every increase of 1 unit in life_exp, there is an associated decrease of, on average, 0.137 units of fert_rate.\n\n    -   \"associated\"\n    -   \"on average\"\n\n## Your first linear regression model\n\n-   Because you might have two countries whose life_exp values differ by 1 unit, but their difference in fertility rates may not be exactly\n\n-   Across all possible countries, the average difference in fertility rate between two countries whose life expectancies differ by one is 0.137\n\n## Observed/fitted values and residuals\n\n-   Observed values\n-   Fitted values\n-   Residual\n\n![](assets/residuals.png)\n\n## Regression with a categorical Variable\n\n-   Does continent influence life expectancy?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapminder2022 <- un_member_states_2024 |>\n  select(country, life_exp = life_expectancy_2022, continent, gdp_per_capita) |> \n  na.omit()\n```\n:::\n\n\n## Explore Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gapminder2022, aes(x = life_exp)) +\n  geom_histogram(binwidth = 5, color = \"white\") +\n  labs(x = \"Life expectancy\", \n       y = \"Number of countries\",\n       title = \"Histogram of distribution of worldwide life expectancies\") +\n  facet_wrap(~ continent, nrow = 2)\n```\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## Explore Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gapminder2022, aes(x = continent, y = life_exp)) +\n  geom_boxplot() +\n  labs(x = \"Continent\", y = \"Life expectancy\",\n       title = \"Life expectancy by continent\")\n```\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n## Categorize by Continent\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlife_exp_by_continent <- gapminder2022 |>\n  group_by(continent) |>\n  summarize(median = median(life_exp), mean = mean(life_exp))\nlife_exp_by_continent\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  continent     median  mean\n  <fct>          <dbl> <dbl>\n1 Africa          66.1  66.3\n2 Asia            75.4  74.9\n3 Europe          81.5  79.9\n4 North America   76.1  76.3\n5 Oceania         74.6  74.4\n6 South America   75.4  75.2\n```\n\n\n:::\n:::\n\n\n## Categorize by Continent\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlife_exp_by_continent |>\n  mutate(diff_africa = (mean - mean[continent == \"Africa\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  continent     median  mean diff_africa\n  <fct>          <dbl> <dbl>       <dbl>\n1 Africa          66.1  66.3        0   \n2 Asia            75.4  74.9        8.64\n3 Europe          81.5  79.9       13.6 \n4 North America   76.1  76.3        9.99\n5 Oceania         74.6  74.4        8.11\n6 South America   75.4  75.2        8.92\n```\n\n\n:::\n:::\n\n\n## Can we fit a best fit line here?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gapminder2022, aes(x = continent, y = life_exp)) +\n  geom_boxplot() +\n  labs(x = \"Continent\", y = \"Life expectancy\",\n       title = \"Life expectancy by continent\")\n```\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n## Linear Regression\n\n-   Dummy/Indicator variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlife_exp_model <- lm(life_exp ~ continent, data = gapminder2022)\n\ncoef(life_exp_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           (Intercept)          continentAsia        continentEurope \n             66.309808               8.639965              13.597867 \ncontinentNorth America       continentOceania continentSouth America \n              9.985410               8.106621               8.917692 \n```\n\n\n:::\n:::\n\n\n## Linear Regression Interpretation\n\n-   Dummy/Indicator variables\n\n-   What does the intercept mean?\n\n-   What does each variable mean?\n\n## Incorporating Confounding\n\n-   What could be potential confounders here?\n\n    -   Directed Acyclic Graphs (DAGs) !\n\n## Incorporating Confounding\n\n-   Lets control/account for income/development\n    -   Confounder\n    -   Control variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUN_data_ch6 <- un_member_states_2024 |>\n  select(country, \n         life_expectancy_2022, \n         fertility_rate_2022, \n         income_group_2024)|>\n  na.omit()|>\n  rename(life_exp = life_expectancy_2022, \n         fert_rate = fertility_rate_2022, \n         income = income_group_2024)|>\n  mutate(income = factor(income, \n                         levels = c(\"Low income\", \"Lower middle income\", \n                                    \"Upper middle income\", \"High income\")))\n```\n:::\n\n\n## Exploratary Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(UN_data_ch6, aes(x = life_exp, y = fert_rate, color = income)) +\n  geom_point() +\n  labs(x = \"Life expectancy\", y = \"Fertility rate\", color = \"Income group\")\n```\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n## Controlling for income\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_no_int <- lm(fert_rate ~ life_exp + income, data = UN_data_ch6)\n\n# Get the coefficients of the model\ncoef(model_no_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              (Intercept)                  life_exp incomeLower middle income \n               10.7676024                -0.1006323                -0.7186537 \nincomeUpper middle income         incomeHigh income \n               -1.2393433                -1.0666572 \n```\n\n\n:::\n:::\n\n\n## Interpretation\n\nAssuming that this model is correct, for any UN member state, every additional year of life expectancy reduces the average fertility rate by 0.101 units, regardless of the income level of the member state.\n\n## Assumption - Parallel slopes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(UN_data_ch6, aes(x = life_exp, y = fert_rate, color = income)) +\n  geom_point() +\n  labs(x = \"Life expectancy\", y = \"Fertility rate\", color = \"Income group\") +\n  geom_parallel_slopes(se = FALSE)\n```\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n## Assumption - Varying slopes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(UN_data_ch6, aes(x = life_exp, y = fert_rate, color = income)) +\n  geom_point() +\n  labs(x = \"Life Expectancy\", y = \"Fertility Rate\", color = \"Income group\") +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](linear_regression_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n## Interacting with income\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_int <- lm(fert_rate ~ life_exp * income, data = UN_data_ch6)\ncoef(model_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       (Intercept)                           life_exp \n                       11.91826460                        -0.11848075 \n         incomeLower middle income          incomeUpper middle income \n                       -1.50420617                        -1.89291757 \n                 incomeHigh income life_exp:incomeLower middle income \n                       -6.57953685                         0.01265027 \nlife_exp:incomeUpper middle income         life_exp:incomeHigh income \n                        0.01117481                         0.07221696 \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "linear_regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}