---
title: 'Coordinate Reference Systems'
author:
- In Class Demonstration \#2 \newline
- GEOG 510, GIS & Spatial Analysis for Public Health \newline
- Varun Goel
output:
  html_document:
    theme: flatly
    highlight: tango
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

For data to be "spatial," the observations must be explicitly tied to locations on the Earth's surface. All spatial data has (or should have) a Coordinate Reference System (CRS), which describes the underlying system used to store location information in the data. Additionally, in QGIS, the Map Panel (canvas) has a CRS defined to display spatial data. It is important to understand that the CRS of the data and the Map Panel serve different (but linked) purposes.

[The data for this demonstration are available here](https://drive.google.com/file/d/1hCXio7-WU2OjsrRVsqx7lAo_Fr68e0oz/view?usp=sharing){target="_blank"} if you would like to follow along. Download the file *GEOG510_demo2_data.zip* to your hard drive (note where you downloaded the file!) and unzip it.

**Note that throughout this document, if I use the term "right click," this means "control click" for Mac users!**

------------------------------------------------------------------------

### CRS of the Map Canvas

1.  Open QGIS. In the top menu, select Project \| New. Move your eyes to the Status bar, which is located at the bottom of the QGIS window. This area contains a decent amount of information about the properties of the Map canvas itself. Notice that, as you move the cursor within the Map canvas, that the location of the cursor is updated (Coordinate).

2.  Note that the Map canvas already has a CRS defined (bottom right of Status bar)! In this case, the CRS is `EPSG:4326` (WGS 84).

### CRS of data layers

3.  In the Browser panel, navigate to the folder `GEOG510_demo2_data`. Right click on the layer CA_tracts_albers located inside CA_tracts_albers.gpkg, and choose Layer Properties. In the Metadata tab, you can find the CRS information for this layer (EPSG:3310 - NAD83 / California Albers - Projected).

4.  Right click on the layer CA_vacc_15_wgs84.shp, and choose Layer Properties. Note that the CRS information for this layer is EPSG:4326 - WGS 84 - Geographic.

5.  In Explorer or Finder, navigate to the folder `GEOG510_demo2_data`. Right/control click on the file CA_vacc_15_wgs84.prj and choose Open With (or similar). On Windows, open with Notepad. On Mac, open with Text Edit. What's contained in this file?

### Working with CRS in QGIS

6.  Drag the layer CA_tracts_albers located inside CA_tracts_albers.gpkg into the Layers panel or directly into the Map canvas. You may get a pop up window asking about a Transformation for the layer. If so, click OK. Now, look at the Status bar. What happened? The CRS of the Map canvas was redefined to match that of the data layer.

7.  Drag the layer CA_vacc_15_wgs84.shp into the Layers panel or directly into the Map canvas. QGIS has projected this layer "on the fly" meaning that, although the data are stored in the WGS 84 CRS, they are being displayed in the California Albers CRS.

8.  In the top menu, go to View \| Panels \| Processing Toolbox. Expand the arrow next to Vector geometry and then click Add geometry attributes. Note the options for Calculate Using! Choose one and click okay. What happened?

9.  In the Layers Panel, right click on CA_vacc_15_wgs84 and choose Export \| Save Features As. Note the options for CRS. Choose Project CRS. Save as CA_vacc_15_albers.gpkg in the `GEOG510_demo2_data` folder.

10. In the Layers Panel, right click on CA_vacc_15_wgs84 and choose Layer CRS. Note the options... one important one is that you can change the Map canvas CRS to match one the layers! Choose Set Project CRS from Layer. What happened?

11. You can also change the Map canvas CRS by clicking on the CRS information in bottom right of Status bar... or by navigating to Project \| Properties!

------------------------------------------------------------------------
