---
title: 'File and Folder Management and Organization'
author:
- GEOG 510, GIS and Spatial Analysis for Public Health \newline
- Varun Goel
output:
  html_document:
    theme: flatly
    highlight: tango
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

Becoming a GIS user means that you will have to interact with files on your computer in a way that many folks have simply not had training in. In the past, almost everyone who used a computer had some form of introductory training in file/folder management. However, changes in modern operating systems have changed how many people interact with files/folders on their computer (which is now search-based). While this simplifies some day-to-day tasks, this leaves a number of people lacking useful experience that helps when learning GIS.

**Note that throughout this document, I use the term "right click". This means "control click" for Mac users!**

------------------------------------------------------------------------

### Quick background readings for beginners (not required, but recommended)

-   [10 File Management Tips to Keep Your Electronic Files Organized](https://www.thebalancesmb.com/computer-file-management-tips-2948083)\
-   [Zen and the Art of File and Folder Organization](https://www.howtogeek.com/15677/zen-and-the-art-of-file-and-folder-organization/)
-   [Windows: Manage Files and Folders with File Explorer](https://www.groovypost.com/howto/windows-10-files-folders-file-explorer/)\
-   [How to Effectively Organize Files and Folders on Your Mac](https://mackeeper.com/blog/organize-mac/)

------------------------------------------------------------------------

### Make life easier for yourself (and your instructor)

**Windows.** Show File Extensions in File Explorer: 1. Click the “View” tab on the ribbon. 2. Activate the “File name extensions” box in the Show/hide section to toggle file extensions on or off. File Explorer will remember this setting until you disable it in the future.

**Mac.** Show Current Path in Finder: Go to View \| Show Path Bar.

------------------------------------------------------------------------

### Take control of location of downloaded files

Most browsers are going to be set up to automatically download a file to your Downloads folder (without asking). This is appalling behavior to be quite honest. Here are instructions on how to set your browser to "ask" where to download files to as the **default** action. This functionality must be enabled for GEOG 510.

-   [Firefox](https://support.mozilla.org/en-US/kb/where-find-and-manage-downloaded-files-firefox?redirectlocale=en-US&redirectslug=Downloads+window#w_change-where-downloads-are-saved) \>\> Choose: Always ask you where to save files
-   [Chrome](https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&hl=en) \>\> Choose: Ask where to save each file before downloading
-   [Safari](http://osxdaily.com/2018/07/01/change-safari-download-location-mac/) \>\> Choose: Ask for each download
-   [Internet Explorer](https://support.microsoft.com/en-us/help/17436/windows-internet-explorer-download-files-from-web#ie=ie-11) \>\> *Not available* (you probably should not be using this browser anyway)
-   [Edge](https://www.digitalcitizen.life/how-change-where-and-how-microsoft-edge-downloads-files) \>\> Choose: Ask me what to do with each download

**General Tip**

-   Most browsers should have functionality to download to a specific location without having to change the default settings. Instead of "left" clicking on a hyperlink, "right" click and find the option such as "Save link as".

------------------------------------------------------------------------

### Copy a filepath or directory / folder path

-   Mac (Finder): Right click on file, hit Option key, choose Copy filename as Path
-   Windows (File Explorer): Hold down Shift, Right click on file, choose Copy as Path

------------------------------------------------------------------------

### Set Up Folders for GEOG 510

On your computer, set up a folder structure for our class. I would suggest having a top-level folder called "GEOG510" (please, **no spaces** in folder names... they hurt my soul). I would suggest setting up separate folders to store readings, lecture notes, and assignment materials.

------------------------------------------------------------------------
