---
title: 'Raster Analysis using LandScan'
author:
- In Class Demonstration \#9 \newline
- GEOG 510, GIS and Spatial Analysis in Public Health \newline
- Varun Goel
output:
  html_document:
  theme: flatly
highlight: tango
mathjax: null
---

```{css, echo=FALSE}
a {
color: royalblue;
}

a:hover {
color: darkorange;
}

div.highlightblock { 
background-color: #e0f0ff; 
  padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

In this demonstration, you will learn some raster analysis operations, and also get exposure to analysis LandScan data, which is commonly used as a high-resolution population dataset for many studies. If you want to follow along, you can [download the data here](https://drive.google.com/file/d/16nVNjk_kFm_8p_oZPzmkYferC_bQ8jPl/view?usp=sharing).

**Note that throughout this document, if I use the term "right click," this means "control click" for Mac users!**

------------------------------------------------------------------------

### Open QGIS

1.  Open a new project in QGIS.

### LandScan Imagery

2.  LandScan imagery for population distribution is available [here](https://landscan.ornl.gov). However, for this demonstration I have already downloaded the 2021 population distribution data for you. For this demo, we are interested in looking population distribution for [**Richland County, SC**]{.underline}.

### Clip Raster Layer

3.  Add the `landscan-usa-2021-conus-day.tif` to your QGIS project. This contains the day-time population count for each pixel.

4.  Add `richland_bg.gpkg` to your QGIS project and accept any transformations.

5.  Clip the landscan layer to the area of interest bounds, which is Richland County. Navigate in the top menu to [**Raster \| Extraction \| Clip Raster by Mask Layer**]{.underline}. For the Input layer choose the landscan layer. For the Mask layer choose richland county block groups. Leave everything else unchanged (this will create a temporary output layer called `Clipped (mask)`). To ensure no confusion layer, rename this temporary layer to `daypop.`

6.  Turn off the original landscan layer and give the new temporary layer a different color ramp that makes sense.

### Basemaps in QGIS

7.  To provide more context to your analysis, you can also add freely available basemaps to QGIS. If you dont have it already, install the `QuickMapServices` in QGIS.

8.  Once installed, go to [**Web \| QuickMapServices \| OSM \| OSM Standard**]{.underline} and insert the Open Street Map basemap.

9.  To make the basemap more visible under the raster layer, you can double click on your raster layer, and increase the transparency using the **Global Transparency** function.

### Raster Calculator

7.  Now, import the `richland_nightpop.tif` raster file to QGIS. This contains the night-time population count for each pixel and has already been clipped.

8.  Now we want to compare the difference between day-time and night-time populations in the area. To make "apples to apples" comparison, it is important that your rasters are in the same color scheme and classes. You can do so easily by ***"transferring styles"*** from one layer to the other. **Simply right click on the daytime population layer \| Styles \| Copy Style.** Then **right click on the nighttime population layer \| Styles \| Paste Style.**

9.  Finally we will calculate the difference between daytime and nighttime populations for each pixel. To do so go to **Processing \| Raster Analysis \| Raster Calculator (not the virtual one)**. In the raster calculator, **select the 2 input layers, and use a subtraction expression to subtract nighttime populations from daytime populations**. Save as a temporary layer. This raster calculator is a very powerful tool for calculations linked to raster overlay.

### Zonal Statistics

10. In many analysis, we want to get information from raster data, and then assign it to vector data. In this case, we want to calculate the nighttime population for each census block group in Richland County. To do so, go to **Processing \| Raster Analysis \| Zonal Statistics.** Provide the Richland BG polygon file as input layer, and the nighttime population file as raster. Statistics to Calculate can be as it is. Create temporary layer.

11. Take a look at the Zonal Statistic layer and examine the distribution of the population.
