---
title: 'Exposure Assessment'
author:
- In Class Exercise \#8 \newline
- 10 points
- GEOG 510, GIS and Spatial Analysis in Public Health \newline
- Varun Goel
output:
  html_document:
    theme: flatly
    highlight: tango
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

In this exercise, you estimate population-level (Census Tract) exposure to Ozone in Los Angeles County, CA. The Ozone layers were created using air quality monitoring data downloaded from the EPA.

**Note that throughout this document, if I use the term "right click," this means "control click" for Mac users!**

------------------------------------------------------------------------

### Data

1.  [Download the data here](https://drive.google.com/file/d/1jUnxGy2Xxq2Bo1AnYIaQtlYFCStxXaW8/view?usp=sharing) and unzip.

### Open QGIS and Load layer

2.  Open QGIS, then open the project file `GEOG510_ex8.qgz`.

3.  Look through the data (but don't change the layer order!)

### Exposure based on Nearest Station

In the following steps, you will be assigning an Ozone value to each tract based on the nearest monitoring station value.

4.  In the Processing Toolbox, navigate to Vector general \| Join Attributes by Nearest. Use the following options (leave everything else unchanged) and click Run:
    -   Input layer: LA_county_tract_centroids
    -   Input layer 2: O3_pts_ca
5.  Table join the resulting layer to the LA_county_tract (polygon) layer. In the LA_county_tract layer, calculate a new field called O3_nearest using the joined **ozone** field. Once this is calculated, remove the table join.

### Exposure based on Pixels Inside Boundary

In the following steps, you will be assigning an Ozone value to each tract based on the average Ozone level of pixels falling within each tract's boundary.

6.  In the Processing Toolbox, navigate to Raster analysis \| Zonal statistics. Use the following options (leave everything else unchanged) and click Run:
    -   Input layer: LA_county_tract
    -   Raster layer 2: Ozone_CA_LA_2023_interp
    -   Statistics to calculate: Mean
7.  Table join the resulting layer to the LA_county_tract (polygon) layer. In the LA_county_tract layer, calculate a new field called O3_zonal using the joined \*\*\_mean\*\* field. Once this is calculated, remove the table join.

### Calculate and Map Difference

8.  In the LA_county_tract layer, calculate a new field called DIFF using the following expression: `"O3_zonal" - "O3_nearest"`

9.  Create a simple map layout showing the tract level differences in exposure estimates. Use a diverging color scheme! The resulting map only needs to have the map and legend. Export as a .png file and upload to your OneDrive folder using the "youruserid_ex8.png" format.
