---
title: 'QGIS Plugins and Geocoding'
author:
- In Class Demonstration \#3 \newline
- GEOG 510, GIS and Spatial Analysis in Public Health \newline
- Varun Goel
output:
  html_document:
    theme: flatly
    highlight: tango
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

The functionality of QGIS can be extended using plugins. Similar to R and other open source software, these are user-contributed. This demonstration will show how to install/manage plugins.

The second part of the demo will show how to geocode using QGIS.

**Note that throughout this document, if I use the term "right click," this means "control click" for Mac users!**

------------------------------------------------------------------------

### Install a Plugin

1.  Open QGIS and start a new project. In the top menu, navigate to Plugins \| Manage and Install Plugins. Note that the popup window has multiple tabs on the left showing all the available plugins, those you have installed, and those you have not installed (and a couple of other options).

2.  Click on the Not Installed tab. In the search bar, type `mmqgis`. You should get a single result. Click on it and review the summary information. This appears to be a general set of vector tools that extends/improves some options in base QGIS. Click the Install Plugin button on the bottom right. Hopefully, you get a message at the top saying it installed successfully! Clear `mmqgis` from the search bar.

3.  Click on the Installed tab. mmqgis is probably checked already (because you just installed it). If it isn't click the check box next to it, then click the Close button. Note that you now have an option for **MMQGIS** in the top menu!

::: highlightblock
#### Where's my plugin?

The location of the functions/operations provided in a QGIS plugin varies by the plugin. For example, the MMQGIS plugin adds a completely new option to the top menu, whereas other may add a set of functions under a submenu such as Vector \| PLUGIN. Generally, this information can be found on the plugin summary at Plugins \| Manage and Install Plugins.
:::

### Geocode data from a .csv file

Within QGIS, MMQGIS provides an option to geocode address locations stored in a .csv file. This is a pretty standard functionality provided by most GIS softwares.

4.  Navigate to <https://gis-michigan.opendata.arcgis.com/datasets/8fc9c089c11a4913b0768381fa07bf6d_0>. Click the **Download** button, scroll down to GeoJSON, and click the **Download** button. Save the file as **MI_County.geojson** to your hard drive (a great place to save would be your GEOG 510 folder).

5.  Download [GEOG510_demo3_data.zip here](https://drive.google.com/file/d/16oRP6jma2O9f4E2c6700b7x2yp2_2eNI/view?usp=share_link){target="_blank"}. A great place to save would be your GEOG 510 folder.

6.  Add MI_County.geojson to the Layers panel. Shield eyes... ouch, that is a nasty CRS (we'll deal with that later).

7.  In the top menu, navigate to MMQGIS \| Geocode \| Geocode CSV with Web Service. Choose **MIhospitals-for-geocoding.csv** from the downloaded **GEOG510_demo3_data** folder as the input. QGIS attemps to find the correct fields for Address, City, and State (here, this was easy). For Web Service, choose OpenStreetMap / Nominatim. Note that there is no option for API Key. For Output File Name, click the little button with three dots and Save As MIhospitals-for-geocoding.**gpkg** in the same location you saved the .csv file. For Not Found Output List, Save As MIhospitals-for-geocoding-notfound.csv in the same location you saved the .csv file. Click Apply. The process will likely take a few minutes. The result should be added to the Layers panel. How many of the hospitals were geocoded?

8.  Change the CRS to Michigan GeoRef.

9.  Open the attribute table of the geocoded layer MIhospitals-for-geocoding. Note the "display_name" and type" fields. These contain some important information about the quality of the results! Close the attribute table, then click "Zoom to Layer" on MIhospitals-for-geocoding. What do we notice? (use Identify tool)

10. Add MIhospitals-for-geocoding-notfound.csv to the Layers panel. These are the features that could not be geocoded.

------------------------------------------------------------------------
