---
title: 'GEOG 531: Final Project'
author:
- 200 points \newline
- GEOG 531, Intro to quantitative methods in Geographic Research \newline
- Varun Goel
date: 'Updated: `r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    theme: flatly
    highlight: null
    mathjax: null
---

```{css, echo=FALSE}
a {
  color: royalblue;
}

a:hover {
  color: darkorange;
}

div.highlightblock { 
 background-color: #e0f0ff; 
 padding: 10px 10px 3px 10px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

------------------------------------------------------------------------

## Overall Project Paper Goal

For your final project paper/report, you are required to implement an analysis that leverages quantitative methods to answer a question that is geographic in nature. Given the breadth of geographic questions that can be asked, you have a lot of freedom in choosing that question. In general, a geographic question would have the following components:

-   There is no minimum or maximum number of operations you need to perform in your analysis, but there are some general principles that you should follow.

1\) You should have a main research question that is related to an outcome, AND also focuses on investigating the role of the underlying process(es) that may have generated the geographic distribution of the outcome that you are interested in. My general advice for this project is aim for a focused, tight, organized, and rigorous analysis, than focusing on a complex question. Infact, I would much rather [**you ask a simple question and answer it very well**]{.underline} than have you ask an awesome question and not do a very good job of answering it.

2\) Your analysis should include some of the [**descriptive statistics and maps**]{.underline} that we have learned in class. The purpose of these is to describe to the reader, important summaries and spatial distribution of variables related to your research question.

3\) Your analysis should include some of the **exploratory quantitative methods and** techniques that we have learned in class. These are techniques that help you [*identify patterns*]{.underline} objectively in your datasets so that you can begin to think about [*what may be the underlying processes*]{.underline} that are driving those patterns that you observe. Ideally, these would either be statistical tests, or various data visualizations that show the process behind your 'educated' guess. The purpose of this part of the analysis is to [**generate a hypothesis**]{.underline} that you want to test (next section)

4\) Ultimately, your main research question should to be **explanatory** in nature, in an attempt to understand, at least on some level, the [*process generating the spatial pattern(s)*]{.underline}. This is where you start generating or testing evidence of whether/how certain processes might generate the spatial pattern of the outcome that you observe. This is where [**you will test your hypothesis**]{.underline} and whether you should be rejected the null hypothesis or not. You will be required to use atleast 1 form of regression modeling for this part of the analysis.

[There may be some exceptions to this rule.]{.underline} I understand that these requirements will be different for everyone's particular project, so [**please talk with me, if you have any doubts or questions.**]{.underline} If you leave everything towards the end, there is no guarantee that I will be able to help you in my full capacity.

------------------------------------------------------------------------

## Paper requirements

The purpose of the final paper is to learn how to communicate the findings of your quantitative analysis to a general academic audience (who may or may not be well-versed with spatial analysis). Below, I have outlined steps and components for the organization of your output.

------------------------------------------------------------------------

## Paper Organization

Barring any exceptions that are communicated with me, your project should have the following components. Details for each section are discussed in the Section Content. Please note that unless mentioned otherwise, both graduate and undergraduate students need to include those components in their final project.

1\) Your project should have a title. Please include your name. Please do not create a separate page with a title/and your name.

2\) Your paper should be roughly organized into the following sections.

-   **Introduction**

    -   Main question/objective\
    -   Background *(graduate students only)*

-   **Materials and Methods**

    -   Data and Preprocessing
    -   Methods\

-   **Results**\

-   **Discussion**

-   **Limitations *(graduate students only)***

-   **Conclusions**\

-   **References**

------------------------------------------------------------------------

## Section Content

#### Introduction

Provides a broad overview of the topic and why it is important (think “big picture” here). Think of your Introduction as a funnel... start with big ideas and narrow down to a problem statement and research question. Your research question should be extremely easy for me (the reader) to identify.

Note: Undergraduate students should aim for only 1 paragraph, while graduate students should have a more comprehensive introduction of 2-3 paragraphs.

##### *Background/Literature Review*

This section falls directly between the Introduction, which should build to your problem statement and research question, and the Materials and Methods, which explains data and method(s) you used to answer your research question. The Background should function as a bridge between these two sections. By reviewing the previous literature, you will be providing additional context to the Introduction content and providing important foundational information that will assist the reader in understanding the motivation or justification for your work (for some, this section also might require a review of your overall analytical approach– but not a deep dive into the methods). Aim for roughly 3-4 paragraphs for this subsection.

#### Materials and Methods

This section will likely be split into Data and Preprocessing and Methods. In GIS-based analysis, it is often the case that there were a number of operations performed to get the data ready for the actual analysis. In a sense, these are not “methods” because they were not analytic methods used to answer the research question. Sometimes, this line is blurry; however, generally, it is pretty easy to separate out what was preprocessing and what was analysis.

##### *Data and Preprocessing*

This section should have link(s) or references to where you acquired the data from. You do not have to provide every single minute detail of the pre-processing steps, but should provide enough detail that another person could reasonably reproduce what you did to acquire and prepare the data for analysis.

##### *Methods*

Here, detail the analytic method(s) that you used to answer the research question. Don't be afraid to use signposts back to your research question(s) here, e.g., “To answer this or that... I used this method”. You should also give a brief justification of why you used the method that you intend to use.

#### Results

This is self explanatory. Again, don't be afraid to use signposts back to your research question(s) here, e.g., “The results of this test answer our question of this or that”. Keep this section straightforward, e.g., save any larger discussion or explanation of what the results “mean” in a broader sense for the following section.

#### Discussion (Limitations) and Conclusions

For undergraduate students this will be one paragraph only. Here is where you can expand upon the broader implications of your results or to compare your results to results from previous studies. You can also use this area to discuss “future research” (not required, but recommended). You should also use this area to critically discuss “limitations” of your analysis. These could be due to data issues, MAUP, not being able to use a more sophisticated method, etc. Wrap up your paper with a short summary of the main takeaways from your analysis.

Graduate students will have a separate section for discussion, limitations, and conclusion.

#### References

List your cited literature.

------------------------------------------------------------------------

## Evaluation

The grading rubric for your project is defined [here](./finalproject/GEOG531_finalProjectGrading.docx)

\*\* *Please start early and get in touch with me if you have any questions regarding anything about the assignment or requirements.* \*\*

------------------------------------------------------------------------

### Timeline

Even if you did not know it, you all have already started thinking about your final paper topics already through data searching for topics of interest to you and map making as part of your assignment components. As we move forward, I will continue to embed parts related to your final project in future assignments. Additionally, I will also have some structured checkpoints till the end of the semester to help ensure that you have all the help needed to execute a final project. If you follow them timely, there is a good likelihood that your final papers will be solid and most importantly stress-free! Here are the suggested checkpoint deadlines:

-   [**Oct 15: Have a finalized main research question and identify datasets of interest.**]{.underline}

    If you have not already, start thinking about your topic of interest and narrow down on a research question based on the data that you have been finding. If you are struggling with ideas about your final projects [**please get in touch with me before and I can help you think about a question or help finding data.**]{.underline}

------------------------------------------------------------------------

### Deliverables

------------------------------------------------------------------------
